---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

##### mysqo

- name: install the nginx rpm from a remote repo
  yum:
    name:  http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present


- name: Install MySQL
  action: yum name={{ item }}
  with_items:
    - MySQL-python
    - mysql
    - mysql-server




- name: Start the MySQL service
  action: service name=mysqld state=started


#- name: update mysql root password for all root accounts
#  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost


- name: Install ansible
  action: yum name={{ item }}
  with_items:
    - ansible
    - git

- name: download file and force basic auth
  get_url:
    url: https://github.com/ansible-semaphore/semaphore/releases/download/v2.3.0/semaphore_linux_amd64
    dest: /tmp/semaphore_linux_amd64
    force_basic_auth: yes


- name: install semaphore
  shell: semaphore_linux_amd64

