---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

##### mysqo

- name: install mysql repo from a remote repo
  yum:
    name:  http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present


- name: Install MySQL
  action: yum name={{ item }}
  with_items:
    - MySQL-python
    - mysql
    - mysql-server




- name: Start the MySQL service
  action: service name=mysqld state=started


#- name: update mysql root password for all root accounts
#  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost


- name: Install ansible
  action: yum name={{ item }}
  with_items:
    - ansible
    - git

- name: install semaphore
  shell: easy_install pexpect

- name: download file and force basic auth
  get_url:
    url: https://github.com/ansible-semaphore/semaphore/releases/download/v2.3.0/semaphore_linux_amd64
    dest: /usr/bin/semaphore
    force_basic_auth: yes
    mode: 0750

- firewalld:
    port: 3000/tcp
    permanent: true
    state: disabled
    
- name: install semaphore
  expect:
    command: /usr/bin/semaphore -setup
    responses:
     #   ' > DB Hostname (default 127.0.0.1:3306): ': "\n"
        
       # '\r\n Hello! You will now be guided through a setup to:\r\n\r\n 1. Set up configuration for a MySQL/MariaDB database\r\n 2. Set up a path for your playbooks (auto-created)\r\n 3. Run database Migrations\r\n 4. Set up initial seamphore user & password\r\n\r\n > DB Hostname (default 127.0.0.1:3306): ': "\n"
       
          "> DB User (default root): "toor"
        timeout: 60
        echo: yes
    register: prompt
    
- debug:
    var: prompt.stdout_lines       
        
     #   ' > DB User (default root): ': "\n"
     #   '> DB Password:': "semaphore\n"
     #   '> DB Name (default semaphore):': "\n"
     #   '> Playbook path: /var/semaphore': "\n"
     #   '> Web root URL (default http://localhost:8010/): ': "\n"
     #   '> Enable email alerts (y/n, default n): ': "\n"        
     #   '> Enable telegram alerts (y/n, default n):': "\n"        
     #   '> Enable LDAP authentication (y/n, default n):': "\n"   
     #   '> Is this correct? (yes/no): yes': "yes\n"   
     #   '> Username:': "danofor\n"           
     #   '> Email: danfor@danfor.it': "danfor@danfor.it\n"
 
      
        
- name: Create directory var
  file: path=/var/semaphore state=directory 
#    mode: 0750

#- name: Create directory ssh
#    file: path=/root/.ssh state=directory 
#    mode: 0750

#- copy: src=files/config
#        dest=/root/.ssh/config
#        mode: 0750
 
